import { Roboto } from 'next/font/google';
import { useEffect } from 'react';
import Head from 'next/head';
import { Provider } from 'react-redux';
import { persistStore } from 'redux-persist';
import { PersistGate } from 'redux-persist/integration/react';
import store from '@/store';
import '../styles/global.css';
import '../styles/app.scss';

const roboto = Roboto({
  subsets: ['latin'],
  weight: ['100', '300', '400', '500', '700', '900'],
});

export default function App({ Component, pageProps }) {
  let persistor = persistStore(store);

  useEffect(() => {
    if ('serviceWorker' in navigator) {
      navigator.serviceWorker.register('/sw.js').then((registration) => {
        let serviceWorker;
        if (registration.installing) {
          serviceWorker = registration.installing;
        } else if (registration.waiting) {
          serviceWorker = registration.waiting;
        } else if (registration.active) {
          serviceWorker = registration.active;
        }

        if (serviceWorker && serviceWorker.state === 'activated') {
          registration?.pushManager?.subscribe({
            userVisibleOnly: true,
            applicationServerKey:
              'BCpQ0NHrKo0Y3h6CfJ97xm-FtJsdWOIHDHNsUWA87F7EyWXbBZJKNRWNrr5eZAL-an25YbUkXVVjVFMjlUkqtEU',
          });
        }
      });
    }
  }, []);
  return (
    <Provider store={store}>
      <PersistGate loading={null} persistor={persistor}>
        <div>
          <Head>
            <meta name="description" content="Generated by create next app" />
            <meta
              name="viewport"
              content="width=device-width, initial-scale=1"
            />
            <meta name="theme-color" content="#4285f4" />
            <link rel="manifest" href="/manifest.json" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
          <style jsx global>{`
            html,
            body {
              font-family: ${roboto.style.fontFamily}!important;
            }
          `}</style>
          <div className="wrapper">
            <Component {...pageProps} />
          </div>
        </div>
      </PersistGate>
    </Provider>
  );
}
